name: Renovate Self-Hosted on GitHub Actions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: true
            fetch-depth: 0
      - name: Check .gitmodules ref
        run: |
          ./maintenance/check_branch.sh
      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.12
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: .github/renovate_global.json
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_PLATFORM: 'github'
